source 'https://rubygems.org'

gem 'rails', "~> 5.1"
gem 'devise'
gem 'haml'
gem 'sassc'
gem 'aws-sdk-s3'
gem 'aws-sdk'

gem 'mongoid'
gem 'mongoid-paperclip'
gem 'ransack', '< 1.8.7'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'activeadmin'
gem 'cancancan'
gem 'ish_models',   :github => 'piousbox/ish_models',   :branch => '1.0.0'
gem 'ish_manager',  :github => 'piousbox/ish_manager',  :branch => :master

## for travis
gem 'i18n', '0.9.1'
gem 'minitest', '5.10.2'
gem 'tzinfo', '1.2.4'
gem 'activesupport', '5.1.4'
gem 'rails-controller-testing'
gem 'rspec'
gem 'rspec-rails'
gem 'factory_girl_rails'
gem 'rake'

group :test, :development do
  gem 'byebug'
  gem 'capybara'
  gem 'httparty'
end
