source 'https://rubygems.org'

gem 'rails', "~> 6.1"
gem 'rake'
gem 'devise'
gem 'haml-rails'
gem 'sassc'
gem 'aws-sdk-s3'
gem 'irb', '>= 1.2.8'
gem 'dotenv-rails'

gem 'jwt'
gem 'json-jwt'
gem 'mysql2'
gem 'discard', '~> 1.2'

gem 'mongoid' # @TODO: I tried removing this dependency from here but could not.
gem 'mongoid-paperclip'
gem 'mongoid_paranoia'
gem 'kaminari'
gem 'kaminari-mongoid'
gem 'cancancan'

gem 'ishapi',         :github => 'wasya-co/ishapi',       :branch => '1.1.0'
gem 'ish_models',     :github => 'piousbox/ish_models',   :branch => '2.2.0'
gem 'ish_manager',    :github => 'piousbox/ish_manager',  :branch => '2.1.0'

group :test, :test_local, :development do
  gem 'byebug'
  gem 'capybara' # @TODO: remove?
  gem 'database_cleaner-mongoid'
  gem 'rspec-rails'
  gem 'factory_bot_rails' # , require: false
  gem 'rails-controller-testing'
end
